project_id = "lhdivfukcinaokardces"

[functions.extract-cv]
verify_jwt = false

[functions.assess-job]
verify_jwt = false

[functions.tailor-cv]
verify_jwt = true

[functions.run-evals]
verify_jwt = false

[functions.cover-letter]
verify_jwt = true
